server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth2-client-app
            client-secret: ndh8xwg9xTQrL2BpFldHjXOXtmd0iTY9
            client-name: oauth2-client-app
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: http://127.0.0.1:8081/login/oauth2/code/keycloak
            scope:
              - openid
              - email
              - profile

        provider:
          keycloak:
            authorization-uri: http://localhost:8080/auth/realms/baeker/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/baeker/protocol/openid-connect/token
            issuer-uri: http://localhost:8080/auth/realms/baeker
            user-info-uri: http://localhost:8080/auth/realms/baeker/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/auth/realms/baeker/protocol/openid-connect/certs
            user-name-attribute: preferred_username